---
apiVersion: v1
kind: Secret
metadata:
  name: broker-users-jaas-config
stringData:
  login.config: |
    activemq {
      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=true
          org.apache.activemq.jaas.properties.user="new-users.properties"
          org.apache.activemq.jaas.properties.role="new-roles.properties";

      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=false
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties"
          baseDir="/home/jboss/amq-broker/etc";
    };
  new-users.properties: |
    quotes-processor=openshift
    quotes-producer=openshift
  new-roles.properties: |
    admin=quotes-processor,quotes-producer
type: Opaque
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-broker
spec:
  acceptors:
    - name: amqp
      port: 5672
      protocols: amqp
    - name: mqtt
      port: 1883
      protocols: mqtt
  adminPassword: openshift
  adminUser: admin
  brokerProperties:
    # Managing scaledown by using the AMQ Broker Operator
    # Reference: https://docs.redhat.com/en/documentation/red_hat_amq_broker/7.14/html-single/deploying_amq_broker_on_openshift/index?extIdCarryOver=true&intcmp=7013a0000026GZMAA2&sc_cid=7015Y000003sysvQAA#high-availability-for-broker-on-ocp_broker-ocp
    - HAPolicyConfiguration.scaleDownConfiguration.enabled=false
    - HAPolicyConfiguration=PRIMARY_ONLY
    - HAPolicyConfiguration.scaleDownConfiguration.discoveryGroup=my-discovery-group
    # true means that the server will add the name of the validated user to messages it sends
    - populateValidatedUser=true
    # true means that the server will not allow any message that doesn't have a validated user, in JMS this is JMSXUserID
    - rejectEmptyValidatedUser=false
    # Address settings
    - addressSettings.#.maxSizeBytes=52428800 # 50MiB
    - addressSettings.#.pageSizeBytes=10485760 # 10MiB
    - addressSettings.#.addressFullMessagePolicy=PAGE
    - addressSettings.#.defaultConsumerWindowSize=1048576
    - addressSettings.#.redeliveryDelay=100
  console:
    expose: true
  deploymentPlan:
    enableMetricsPlugin: true
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: true
    persistenceEnabled: true
    requireLogin: true
    size: 1
    extraMounts:
      secrets:
        - broker-users-jaas-config
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 50m
        memory: 1024Mi
  env:
    # Reference: https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#tuning_defaults_for_containers
    - name: JAVA_ARGS_APPEND
      value: '-XX:MaxRAMPercentage=75'
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amq-broker
  labels:
    ActiveMQArtemis: amq-broker
spec:
  selector:
    matchLabels:
      ActiveMQArtemis: amq-broker
  endpoints:
    - path: /metrics
      port: console-jolokia
      scheme: http