---
apiVersion: v1
kind: Secret
metadata:
  name: broker-users-jaas-config
stringData:
  login.config: |
    activemq {
      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=true
          org.apache.activemq.jaas.properties.user="new-users.properties"
          org.apache.activemq.jaas.properties.role="new-roles.properties";

      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=false
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties"
          baseDir="/home/jboss/amq-broker/etc";
    };
  new-users.properties: |
    quotes-processor=openshift
    quotes-producer=openshift
  new-roles.properties: |
    admin=quotes-processor,quotes-producer
type: Opaque
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-broker
spec:
  acceptors:
    - name: amqp
      port: 5672
      protocols: amqp
    - name: mqtt
      port: 1883
      protocols: mqtt
  adminPassword: openshift
  adminUser: admin
  brokerProperties:
    # true means that the server will add the name of the validated user to messages it sends
    - populateValidatedUser=true
    # true means that the server will not allow any message that doesn't have a validated user, in JMS this is JMSXUserID
    - rejectEmptyValidatedUser=false
    # Number of journal files to initially create when the broker starts.
    - journalMinFiles=2
    # Number of files to keep after reclaiming unused files. The default value of -1 means that no files are deleted during cleanup.
    - journalPoolFiles=10
    # The size (in bytes) of each journal file.
    - journalFileSize=10485760
    # Whether or not to suppress SESSION_CREATED and SESSION_CLOSED notifications. 
    # Set to true to reduce notification overhead. 
    # However, these are required to enforce unique client ID utilization in a cluster for MQTT clients.
    - suppressSessionNotifications=true
  console:
    expose: true
  deploymentPlan:
    enableMetricsPlugin: true
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: true
    persistenceEnabled: true
    requireLogin: true
    size: 1
    extraMounts:
      secrets:
      - "broker-users-jaas-config"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amq-broker
  labels:
    ActiveMQArtemis: amq-broker
spec:
  selector:
    matchLabels:
      ActiveMQArtemis: amq-broker
  endpoints:
  - path: /metrics
    port: console-jolokia
    scheme: http